Honan/Pages/ClubManagement/CLI_CertificateOfCurrency.cshtml.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Honan.wwwroot;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Honan
{
    public class CLI_CertificateOfCurrencyModel : PageModel
    {
        private IWebHostEnvironment _hostingEnvironment;
        private IDataService dataService;
        public CLI_CertificateOfCurrencyModel(IWebHostEnvironment hostingEnvironment, IDataService dataService)
        {
            this._hostingEnvironment = hostingEnvironment;
            this.dataService = dataService;
        }
        [BindProperty(SupportsGet = true)]
        public string stateAbbr { get; set; }
        public string clubName { get; set; }
        public SelectList States { get; set; }

        public void OnGet()
        {
            States = new SelectList(dataService.GetStates(), nameof(State.Abbreviation), nameof(State.Name));
        }
        public JsonResult OnGetClubs(string stateName)
        {
            return new JsonResult(dataService.GetClubs(stateName));
        }


        public async Task<IActionResult> OnPostDownloadAsync(string stateAbbr, string clubName)
        {
            if (clubName != null && clubName != "")
            {
                byte[] rawData = PDFGenerator.ReplaceText(_hostingEnvironment.WebRootPath + "\\downloads\\ClubManagement\\HOCKEY AUSTRALIA LIMITED - Liability COC FINAL.pdf", clubName);
                return File(rawData, "application/pdf");
            }
            else
            {
                return null;
            }
        }
    }
}

Honan/Pages/ClubManagement/CLI_UpgradingCover.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Honan
{
    public class CLI_UpgradingCoverModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

Honan/Pages/ClubManagement/ClubLiabilityInsurance.cshtml.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Honan
{
    public class ClubLiabilityInsuranceModel : PageModel
    {
        public void OnGet()
        {

        }

        public async Task<IActionResult> OnPostDownloadAsync(string downLoadType)
        {
            string path = null;
            if (downLoadType == "PolicyWording")
            {
                
                    path = Path.Combine(
                            new String[5] { Directory.GetCurrentDirectory(),
                              "wwwroot",
                              "downloads",
                              "ClubManagement",
                              "Association_Liability_Policy_Wording_11.18.pdf" });
            }
            else if (downLoadType == "InsuranceSchedule")
            {
                path = Path.Combine(
                            new String[5] { Directory.GetCurrentDirectory(),
                              "wwwroot",
                              "downloads",
                              "ClubManagement",
                              "HOCKEY AUSTRALIA LIMITED - Liability Schedule.pdf" });
            }

            var memory = new MemoryStream();
            using (var stream = new FileStream(path, FileMode.Open))
            {
                await stream.CopyToAsync(memory);
            }
            memory.Position = 0;

            return File(memory, GetContentType(path), Path.GetFileName(path));
        }

        private string GetContentType(string path)
        {
            var types = GetMimeTypes();
            var ext = Path.GetExtension(path).ToLowerInvariant();
            return types[ext];
        }

        private Dictionary<string, string> GetMimeTypes()
        {
            return new Dictionary<string, string>
            {
                {".txt", "text/plain"},
                {".pdf", "application/pdf"},
                {".doc", "application/vnd.ms-word"},
                {".docx", "application/vnd.ms-word"},
                {".xls", "application/vnd.ms-excel"},
                {".xlsx", "application/vnd.openxmlformatsofficedocument.spreadsheetml.sheet"},
                {".png", "image/png"},
                {".jpg", "image/jpeg"},
                {".jpeg", "image/jpeg"},
                {".gif", "image/gif"},
                {".csv", "text/csv"}
            };
        }
    }
}

Honan/Pages/ClubManagement/CLI_CertificateOfCurrency.cshtml
@page
@model Honan.CLI_CertificateOfCurrencyModel
@{
    ViewData["Title"] = "CLI_CertificateOfCurrency";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

<div>
    <section class="justify-content-center">
        <div class="container">
            <div class="row">
                <div class="col-2">
                    <div class="container justify-content-end">
                        <div style="float:right;width:auto;overflow:hidden;padding-top:1em">
                            <a class="hover-effect text-decoration-none pr-2" asp-page="ClubLiabilityInsurance">
                                <div class="d-flex flex-column py-2" style="font-size:small">
                                    <img src="~/image/Common/Back_ICON.svg" alt="..." class="img-title-button img-responsive" width="40" height="40">
                                </div>
                            </a>
                        </div>
                        <div style="float:right;width:auto;overflow:hidden;padding-right:1em;padding-top:1em">
                            <a class="hover-effect text-decoration-none pr-3 pt-3" asp-page="/Index">
                                <div class=" d-flex flex-column py-2" style="font-size:small">
                                    <img src="~/image/Common/Home_ICON.svg" alt="..." class="img-title-button img-responsive" width="40" height="40">
                                </div>
                            </a>
                        </div>
                    </div>
                </div>
                <div class="col-9">
                    <div class="container pb-0" style="margin:20px;">
                        <div class="row pb-0 blueGradient">
                            <div class="col-12 p-0 mb-n4 blueGradient" style="z-index:10;">
                                <div class="row text-white">
                                    <div class="col" style="margin: 20px;">
                                        <div style="font-size: 26px;">
                                            Club Management Liability
                                        </div>
                                        <div style="font-size: 26px;">
                                            Certificate of Cover
                                        </div>
                                        <div style="font-size: 12px;">
                                            A Certificate of Currency is a legal document that demonstrates you have current
                                            Club Management Liability Insurance.</br>
                                            This document is sometimes required by Council and/or Facility Management.
                                        </div>
                                    </div>
                                    <div class="col">
                                        <img src="~/image/ClubManagement/ClubMan_COC_IMAGE.png" alt="..." class="rounded-lg" style="width: 90%;">
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row mt-n4">
                            <div class="col-12 pl-0 pr-0 bg-light">
                                <div class="card border-dark pt-0 pl-0 border-left-0 border-right-0 border-top-0">
                                    <div class="card-header bg-dark text-white">
                                        Enter your club or association details
                                    </div>
                                    <div class="card-body">
                                        <div class="container">
                                            <form asp-page-handler="Download" method="post" target="_blank">
                                                <div class="form-row">
                                                    <div class="form-group col-md-9">
                                                        <label for="inputState" class="font-weight-bold">State</label>
                                                        <select id="inputState" asp-for="stateAbbr" asp-items="Model.States">
                                                            <option value="">Choose ...</option>
                                                        </select>
                                                    </div>
                                                </div>
                                                <div class="form-row">
                                                    <div class="form-group col-md-9">
                                                        <label for="inputClub" class="font-weight-bold">Club/Association</label>
                                                        <select id="inputClub" asp-for="clubName" disabled>
                                                            <option selected>Choose...</option>
                                                        </select>
                                                    </div>
                                                </div>
                                                <input type="image" disabled src="~/image/Common/Download_BTTN.svg" name="saveForm" class="submit" id="saveForm" style="width:120px; height:40px;" />
                                            </form>
                                            <div class="row d-flex justify-content-start mt-2">
                                                <div class="container">
                                                    <div class="col-12">
                                                        <p style="font-size:small; font-weight:700">If you are unable to find your club/association, please contact Honan for assistance.</p>
                                                    </div>
                                                    <div class="col-12">
                                                        <p style="font-size:small; font-weight:700">Phone: <span style="color:darkblue">+61 03 9947 4343</span></p>
                                                    </div>
                                                    <div class="col-12">
                                                        <p style="font-size:small; font-weight:700">Email: <a class="text-decoration-none" style="color:darkblue" href="mailto:info@honan.com.au">info@honan.com.au</a></p>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-1"></div>
            </div>
        </div>
    </section>
</div>


@section scripts{

    <script>
        $("#inputClub").prop("disabled", true);
        $("#saveForm").prop("disabled", true);
        $(function () {
            $("#inputState").on("change", function () {
                var stateName = $(this).val();
                $("#inputClub").empty();
                $("#saveForm").prop("disabled", true);
                $("#inputClub").prop("disabled", true);
                $("#inputClub").append("<option value=''>Choose ...</option>");
                $.getJSON('?handler=Clubs&stateName=' + stateName, (data, status, xhr) => {
                    $("#inputClub").prop("disabled", false);
                    $.each(data, function (i, item) {
                        $("#inputClub").append('<option value="' + item.name + '">' + item.name + '</option>');
                    });
                });
            });
        });

        $(function () {
            $("#inputClub").on("change", function () {
                $("#saveForm").prop("disabled", false);
            });
        });
    </script>
}

Honan/Pages/ClubManagement/CLI_UpgradingCover.cshtml
@page
@model Honan.CLI_UpgradingCoverModel
@{
    ViewData["Title"] = "CLI_UpgradingCover";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

<div>
    <section class="justify-content-center">
        <div class="container">
            <div class="row">
                <div class="col-2">
                    <div class="container justify-content-end">
                        <div style="float:right;width:auto;overflow:hidden;padding-top:1em">
                            <a class="hover-effect text-decoration-none pr-2" asp-page="ClubLiabilityInsurance">
                                <div class=" d-flex flex-column py-2" style="font-size:small">
                                    <img src="~/image/Common/Back_ICON.svg" alt="..." class="img-title-button img-responsive" width="40" height="40">
                                </div>
                            </a>
                        </div>
                        <div style="float:right;width:auto;overflow:hidden;padding-right:1em;padding-top:1em">
                            <a class="hover-effect text-decoration-none pr-3 pt-3" asp-page="/Index">
                                <div class=" d-flex flex-column py-2" style="font-size:small">
                                    <img src="~/image/Common/Home_ICON.svg" alt="..." class="img-title-button img-responsive" width="40" height="40">
                                </div>
                            </a>
                        </div>
                    </div>
                </div>
                <div class="col-9">
                    <div class="container pb-0">
                        <div class="row pb-0 blueGradient">
                            <div class="col-12 p-0 mb-n4 blueGradient" style="z-index:10;">
                                <div class="row text-white">
                                    <div class="col" style="margin: 20px;">
                                        <div style="font-size: 26px;">
                                            Club Management Insurance
                                        </div>
                                        <div style="font-size: 26px;">
                                            Upgrading Cover
                                        </div>
                                        <div style="font-size: 12px;">
                                            All clubs receive the basic level of cover chosen by your hockey State or Territory association for
                                            Non-Medicare Medical and Loss of Income benefits. Clubs, Teams and Individuals can choose to
                                            upgrade from the standard level of cover to a higher level of cover providing players with increased
                                            benefits and reimbusements of Non-Medicare Medical Benefits and to provide a higher weekly benefit
                                            in respect to loss of earnings.</br>
                                        </div>
                                    </div>
                                    <div class="col">
                                        <img src="~/image/ClubManagement/ClubMan_UPCVR_IMAGE.png" alt="..." class="rounded-lg" style="width: 90%;">
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="pt-0">
                                <div class="bg-light" style="border-radius:5px;opacity: 0.5; font-weight:600; color:black">
                                    <div class="row pl-4" style="margin: 20px;">
                                        <div class="col-12 p-0 mb-n1 pl-2">
                                            <p style="font-size:small;">
                                                Upgrading cover is <i>optional</i>.
                                            </p>
                                            <p style="font-size:small;">
                                                Clubs should consider the costs to players and inform members of all decisions made by the club in regard to
                                                upgrading cover.
                                            </p>
                                        </div>
                                        <div class="col-12">
                                            <p style="font-size:small;">If you would like more information on Upgrading Cover please contact Honan on:</p>
                                        </div>
                                        <div class="col-12">
                                            <p style="font-size:small; font-weight:700">Phone: <span style="color:darkblue">+61 03 9947 4343</span></p>
                                        </div>
                                        <div class="col-12">
                                            <p style="font-size:small; font-weight:700">Email: <a class="text-decoration-none" style="color:darkblue" href="mailto:info@honan.com.au">info@honan.com.au</a></p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-1"></div>
            </div>
        </div>
    </section>
</div>

Honan/Pages/ClubManagement/ClubLiabilityInsurance.cshtml
@page
@model Honan.ClubLiabilityInsuranceModel
@{
    ViewData["Title"] = "ClubLiabilityInsurance";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

<section style="background-color:#22272D">
    <div class="container">
        <div class="row">
            <div class="col-9">
                <div class="container pt-1 pb-0">
                    <div class="row justify-content-md-end">
                        <div class="col col-lg-2 d-flex" style="padding: 0px">
                            <a class="flex-fill hover-effect text-decoration-none pr-3" asp-page="/Index">
                                <div class=" d-flex flex-column float-right justify-content-end py-2" style="font-size:small">
                                    <img src="~/image/Common/Home_ICON.svg" alt="..." class="img-title-button img-responsive" width="40" height="40">
                                </div>
                            </a>
                        </div>

                        <div class="col col-lg-2 d-flex" style="padding: 1px; padding-bottom: 4px;">
                            <a class="img-title-button card text-center border-secondary flex-fill hover-effect text-decoration-none" target="_blank" href="https://www.sportscover.com/claims/">
                                <div class="nav-secondary card-body text-dark d-flex flex-column align-items-center justify-content-center py-2" style="font-size:small">
                                    <div class="row">
                                        <div class="col">
                                            <span>
                                                Claims Form
                                            </span>
                                        </div>
                                    </div>
                                </div>
                            </a>
                        </div>
                        <div class="col col-lg-3 d-flex" style="padding:1px; padding-bottom: 4px;">
                            <a class="img-title-button card text-center flex-fill border-secondary hover-effect text-decoration-none" asp-page="CLI_CertificateOfCurrency">
                                <div class="nav-secondary card-body text-dark d-flex flex-column align-items-center justify-content-center py-2" style="font-size:small">
                                    <div class="row">
                                        <div class="col">
                                            <span>
                                                Certificate of Currency
                                            </span>
                                        </div>
                                    </div>
                                </div>
                            </a>
                        </div>
                        <div class="col col-lg-2 d-flex" style="padding:1px; padding-bottom: 4px;">
                            <a class="img-title-button card text-center  border-secondary flex-fill hover-effect text-decoration-none" asp-page="CLI_UpgradingCover">
                                <div class="nav-secondary card-body text-dark d-flex flex-column align-items-center justify-content-center py-2" style="font-size:small">
                                    <div class="row">
                                        <div class="col">
                                            <span>
                                                Upgrade Cover
                                            </span>
                                        </div>
                                    </div>
                                </div>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<section>
    <div class="row d-flex justify-content-center spacing-row">
        <div class="container pr-0 pl-0">
        </div>
    </div>
    <div class="row d-flex justify-content-center">
        <div class="col-md-5 col-sm-10" style="width:100%; min-height:402px;">
            <div class="row">
                <div class="col-sm pink productPageSummaryTitle productPageSummaryTitleText">
                    <div class="row">
                        <div class="col-8  justify-content-start align-middle">
                            <img class="productPageTitleImage" src="~/image/ClubManagement/ClubMan_ICON_LG.svg" />
                            <span>Club Management Liability Insurance</span>
                        </div>
                        <div class="col-4">
                            <div class="row" style="font-size:smaller">
                                Insurer
                            </div>
                            <div class="row" style="font-size:12px">
                                Sportscover Australia Pty. Ltd.
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-12" style="padding: 0px;">
                    <img style="width:100%" src="~/image/ClubManagement/ClubMan_BANNER_2.png" />
                </div>
            </div>

            <div class="row productPageSummaryTitleText bluegradientbackground">
                <div class="col-12" style="font-size:medium">
                    What is Club Management and Professional Liability Insurance?
                </div>
                <div class="col-12" style="font-size:12px">
                    <p>
                        When you give your time an energy to a club, you want to make certain you are not risking your personal or the organisation’s financial security.  That’s why you need a Management and Professional insurance policy.  It provides protection for you and the organisation in the event of legal action.

                    </p>
                </div>
                <div class="col-12" style="font-size:12px;">
                    <p>
                        The insurance addresses exposures//wrongdoings clubs and associations face everyday, including;
                        discrimination, harassments, wrongful termination, inefficient administration or supervision, libel and slander, misrepresentations
                        and employee theft.
                    </p>
                </div>
            </div>
            <div class="row">
                <div class="col-4 pt-2 sideGreySection">
                    <div class="row">
                        <div class="col-12 subHeading">
                            Who Is Covered
                        </div>
                        <div class="col-12" style="font-size:12px">
                            All incorporated hockey clubs, affiliations and
                            associations of each State and Territory.

                        </div>
                    </div>
                    <div class="row pt-4">
                        <div class="col-12 subHeading">
                            Dont't forget
                        </div>
                        <div class="col-12" style="font-size:12px">
                            Management & Professional Liability insurance
                            is ONLY available to incorporated entities!
                            If your club is not incorporated, individual
                            committee members run the risk of exposing
                            their home, car and financial assets.

                        </div>
                    </div>
                    <div class="row pt-4">
                        <div class="col-12 subHeading">
                            Hot Tip...
                        </div>
                        <div class="col-12" style="font-size:12px">
                            It is strongly recommended that you implement
                            a programme to ensure that all claims are
                            Identified and notified immediately and within
                            the policy period to avoid the possibility of a
                            claim being denied.
                        </div>
                    </div>
                </div>
                <div class="col-8 pt-2 pl-5 mainSection">
                    <div class="row subHeading">
                        Coverage Limits & Excess
                    </div>
                    <div class="row" style="font-size:12px">
                        <div class="col-6">
                            Directors & Officers <br />
                            $3,000,000 <br />
                            (Nil Excess)
                        </div>
                        <div class="col-6">
                            <form asp-page-handler="Download" method="post">
                                <input type="hidden" name="downLoadType" value="InsuranceSchedule" />
                                <input type="image" src="~/image/Common/Sched_Download_BTTN.svg" name="saveForm" class="btTxt submit rounded" id="saveForm" style="width:120px; height:40px;" />
                            </form>
                        </div>
                    </div>
                    <div class="row mt-3" style="font-size:12px">
                        <div class="col-6">
                            Employment Practices <br />
                            $500,000 <br />
                            ($25,000 Excess)<br />
                        </div>
                        <div class="col-6">
                            <form asp-page-handler="Download" method="post">
                                <input type="hidden" name="downLoadType" value="PolicyWording" />
                                <input type="image" src="~/image/Common/Word_Download_BTTN.svg" name="saveForm" class="btTxt submit rounded" id="saveForm" style="width:120px; height:40px;" />
                            </form>
                        </div>
                    </div>
                    <div class="row mt-3" style="font-size:12px">
                        <div class="col-6">
                            Commercial Crime <br />
                            $500,000 <br />
                            ($25,000 Excess)<br />
                        </div>
                        <div class="col-6">
                        </div>
                    </div>
                    <hr />
                    <div class="row pt-1">
                        <div style="font-size:small">
                            <span>Coverage provided within a Management and Professional Liability</span>
                        </div>
                        <div style="font-size:12px">
                            <b>Directors and Officers Liability</b> - coverage for any wrongful act including a criminal charge, defamation, civil proceeding or fraudulent act.
                            <br />
                            <b>Employment Practices Liability</b> - includes wrongful dismissal, discrimination or unlawful acts in the workplace.
                            <br />
                            <b>Employee Theft Coverage</b>
                        </div>
                    </div>
                    <hr />
                    <div class="row pt-1">
                        <div style="font-size:small">
                            <span>Examples of Management and Professional Liability Claims</span>
                        </div>
                        <div style="font-size:12px">
                            <b>
                                Directors and Officers Liability
                            </b> - legal action is taken against the club for defamation of a club member.  This came about as a result of information printed in the monthly club newsletter.<br />
                            <b>
                                Employment Practices Liability
                            </b> - legal action is taken against the club for the unfair dismissal of a senior coach.<br />
                            <br />
                            <b>
                                Employee Theft Coverage
                            </b> - the club treasurer has been stealing money from the accounts over a period of time and the club now needs to claim losses.<br />
                            <br />
                        </div>
                    </div>
                    <hr />
                    <div class="row pt-1">
                        <div style="font-size:small">
                            <span>Important Note</span>
                        </div>
                        <div style="font-size:12px">
                            The Directors and Officers and Employment Practices Liability sections of this policy are written on a ‘Claims Made Basis.’  This means that coverage is provided for claims that are notified to the insurer during the period of cover.
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row d-flex justify-content-center spacing-row">
        <div class="container pr-0 pl-0">
        </div>
    </div>
</section>